{% set name = "flask-debugtoolbar" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Flask-DebugToolbar-{{ version }}.tar.gz
  sha256: ccd6a72119ea4f7c486823591b2b2f4a14dc7fb38d6bd495272e0ebdc08724cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.6
    - flask >=0.8
    - blinker
    - packaging
    - itsdangerous
    - werkzeug
    - markupsafe

test:
  imports:
    - flask_debugtoolbar
    - flask_debugtoolbar.panels
    - flask_debugtoolbar.compat
    - flask_debugtoolbar.toolbar
    - flask_debugtoolbar.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://flask-debugtoolbar.rtfd.org/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A toolbar overlay for debugging Flask applications.
  dev_url: https://github.com/mgood/flask-debugtoolbar
  doc_url: http://flask-debugtoolbar.rtfd.org/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
