{% set name = "Flask-DebugToolbar" %}
{% set version = "0.10.1" %}
{% set compress_type = "tar.gz" %}
{% set sha256 = "ec810083123aae0632eb32ba11e1cb4cdace81e7ce6c5009dd06c5204afbce52" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ sha256 }}

build:
  number: 1001
  script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - flask >=0.8

test:
  imports:
    - flask_debugtoolbar
    - flask_debugtoolbar.panels
    - flask_debugtoolbar.compat
    - flask_debugtoolbar.toolbar
    - flask_debugtoolbar.utils

about:
  home: http://flask-debugtoolbar.rtfd.org/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'A toolbar overlay for debugging Flask applications.'
  dev_url: https://github.com/mgood/flask-debugtoolbar
  doc_url: http://flask-debugtoolbar.rtfd.org/

extra:
  recipe-maintainers:
    - pmlandwehr
