{% set name = "flask-debugtoolbar" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3b925d4dcc09205471e5021019dfeb0eb6dabd6c184de16a3496dfb1f342afe1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.6
    - flask >=2.3.0
    - blinker
    - packaging
    - itsdangerous
    - werkzeug
    - markupsafe

test:
  imports:
    - flask_debugtoolbar
    - flask_debugtoolbar.panels
    - flask_debugtoolbar.compat
    - flask_debugtoolbar.toolbar
    - flask_debugtoolbar.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://flask-debugtoolbar.rtfd.org/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A toolbar overlay for debugging Flask applications.
  dev_url: https://github.com/mgood/flask-debugtoolbar
  doc_url: http://flask-debugtoolbar.rtfd.org/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
