appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: nqyuaOyGsZy2mr3GVFRmtVBEjBQAn2CM2ep19mRhZpQtlIm0EHaVU2/DdAzLNrQxxju7kk4JRpkHEGKgGB/zom17hILu1Ii3laIoBpDkskNVTdGju0TrgaBNyqazA3GSqB3lNUAJD/NGyP7qzXr34sUvgNKp26SnCVjBvNHeP101Vv4MuQW6XfKGHeqIp4z0LL08T1xN0QZ7lIk5MxpVkMd7TWHegbTh5CBUMkSpSm4LuKAkPmOcm+Rsw79FYqD77Pi8oZiKUIDhrt1L9+NcqqpwWqdWaFh20PLO/EpBotOPVUfeGKzfLG2XK4ZMeqUFp12r0Rb9KlmXdDOhf3rwudetPC4xPEOHDE6a+Xe8GGpxf9hnLL7atDDVP0Dj9Qsc8a2QRuCOfkPkRCa95H+0O19qXaSms6XJ+mR2KffyvyEx2u/3DphOVt5FhoPs1jAdKsLcV0dzg9Jrl35f/jU7WbZ8/k9/EN6tLF3YJiA2j6JlXNe+j7A4jaBbc6qXK2nJcwp1/lgAG3Z2sVyP6PtnzwnTU3gxZJrrYbWBFm3njjxA8QXoXVhAm57i6rw1KO2z+Uwgv7gtdfI7i5/VZfcF4ZHpU7trywz0osVRIr8Wxl/BtkLL8wcOKn0T+qpz0ms5Mp2amwLMpRCO1Svm/ycCXhKt8cpQkw7o/hT4nYA4sqU=}
